## TensorFlow 1.X




### Instalando o TensorFlow 1.X



In [ ]:
!pip uninstall -y tensorflow #Comando necessário, pois o TensorFlow-gpu não desinstala a versão mais recente do Tensorflow, pode gerar conflitos.

Found existing installation: tensorflow 2.6.0
Uninstalling tensorflow-2.6.0:
  Successfully uninstalled tensorflow-2.6.0


In [ ]:
!pip install tensorflow-gpu==1.15 #Ignorar mensagem de erro

     |████████████████████████████████| 411.5 MB 3.2 kB/s 
     |████████████████████████████████| 3.8 MB 61.5 MB/s 
     |████████████████████████████████| 50 kB 5.8 MB/s 
     |████████████████████████████████| 503 kB 70.9 MB/s 
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7554 sha256=d5a0bc0dfe6bd05e03a3b73696ad56519dd9939c80eb28f04c9ea3b0a0405c0a
  Stored in directory: /root/.cache/pip/wheels/21/7f/02/420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3
Successfully built gast
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.6.0
    Uninstalling tensorflow-estimator-2.6.0:
      Successfully uninstalled tensorflow-estimator-2.6.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.6.0
    Uninstalling tensorboard-2.6.0:
      Successfully uninstalled tensorboard-2.6.0
  Attempting uninstall: gast
    Found existing installation: gast 0.4.0
    Uninstalling gast-0.4.0:
      Succe

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'1.15.0'

### Constantes

#### Definindo uma constante

In [ ]:
# Definindo uma constante no TensorFlow
tensor = tf.constant([[23, 4], [32, 51]])

In [ ]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [ ]:
# Se uma sessão não for inicializada, não podemos acessar os valores da constante
tensor.eval()

ValueError: ignored

#### Acessando os valores de uma constante

In [ ]:
session = tf.Session()

In [ ]:
session.run(tf.global_variables_initializer())

In [ ]:
tensor_value = session.run(tensor)

In [ ]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

### Variáveis

#### Definindo uma variável

In [ ]:
# Definindo uma variável no TensorFlow
variable = tf.Variable([[30, 20], [10, 45]])

In [ ]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [ ]:
# Se uma sessão na for inicializada, não podemos acessar os valores das variáveis
variable.eval()

ValueError: ignored

#### Acessando os valores de uma variável

In [ ]:
# Inicializando uma sessão
session = tf.Session()

In [ ]:
# Inicializando TODAS as variáveis de uma seção
session.run(tf.global_variables_initializer())

In [ ]:
# Executando o método eval no ambiente com a sessão inicializada para conseguir buscar os valores
variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

## TensorFlow 2.0

### Instalando o TensorFlow 2.0

In [ ]:
!pip install tensorflow-gpu==2.0.0

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
tf.__version__

'2.0.0'

### Constantes

#### Definindo uma constante

In [ ]:
# Definindo uma constante no TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [ ]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [ ]:
# Acessando as dimensões de um tensor
tensor_20.shape

TensorShape([2, 2])

#### Acessando os valores de uma constante

In [ ]:
# Acessando os valores de um tensor com o numpy e sem precisar de uma sessão
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [ ]:
# Podemos converter um numpy array para um tensor do TensorFlow
numpy_tensor = np.array([[23,  4], [32, 51]])

In [ ]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [ ]:
tensor_from_numpy

<tf.Tensor: id=1, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Variáveis

#### Definindo uma variável

In [ ]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Acessando os valores de uma variável

In [ ]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Alterando um valor específico de uma variável

In [ ]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [ ]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operações com tensores

In [ ]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=20, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Adição entre um escalar e um tensor

In [ ]:
tensor + 2

<tf.Tensor: id=22, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplicação entre um escalar e um tensor

In [ ]:
tensor * 5

<tf.Tensor: id=24, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Usando funções do numpy nos tensores do TensorFlow

In [ ]:
# Obtendo o quadrado de todos os membros de um tensor
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [ ]:
# Obtendo a raiz quadrada de todos os membros de um tensor
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Dot product (produto escalar) entre dois tensores

In [ ]:
tensor

<tf.Tensor: id=20, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [ ]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Strings no TensorFlow 2.0

In [ ]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=25, shape=(), dtype=string, numpy=b'TensorFlow'>

#### Operações simples com strings

In [ ]:
tf.strings.length(tf_string)

<tf.Tensor: id=26, shape=(), dtype=int32, numpy=10>

In [ ]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=30, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

#### Armazenando arrays (vetores) de strings

In [ ]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [ ]:
# Iterating through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
